### ISSUE TITLE
Remove unnecessary require_once

### ISSUE THREAD

**Issue by ssahara** [tqdv/dokuwiki-diffpreview#2]
Since plugin's action component (action.php file) only define classes, the guards are not necessary.
Also, DokuWiki has a robust autoloading in place since long ago, so custom require statements are no longer needed.

https://github.com/tqdv/dokuwiki-diffpreview/blob/e608cbad6ed9ba5a8605e18d9a7a5c2b5d2c49b7/action.php#L3-L6

**Comment by tqdv** [comment]
Done and updated the plugin. cf. commit 7557fc0

**Comment by ssahara** [comment]
Thanks!
